// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0nk-nMpbnuDdg8IJQI8ei0fPcjWBnRqU',
    appId: '1:58645764182:web:0bb8f57c1964facbc9c3f7',
    messagingSenderId: '58645764182',
    projectId: 'flutter-project-nuenta',
    authDomain: 'flutter-project-nuenta.firebaseapp.com',
    storageBucket: 'flutter-project-nuenta.appspot.com',
    measurementId: 'G-9LY7PRCFP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjik6AFO6vY9Q3l1ci3US5BWvQhvEptjU',
    appId: '1:58645764182:android:3d4f608725d316eac9c3f7',
    messagingSenderId: '58645764182',
    projectId: 'flutter-project-nuenta',
    storageBucket: 'flutter-project-nuenta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_naf7_Ki1ixe054OQXE55u7G7W3DS00o',
    appId: '1:58645764182:ios:2a5b8fec0e8911bac9c3f7',
    messagingSenderId: '58645764182',
    projectId: 'flutter-project-nuenta',
    storageBucket: 'flutter-project-nuenta.appspot.com',
    iosClientId: '58645764182-qtoouscghtmg0q5df15kgr7r5l7p8ckl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapboxNavigation',
  );
}
